CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,

    profileImageUrl VARCHAR(500) DEFAULT NULL,

    role ENUM('USER', 'STUDENT', 'ALUMNI', 'ADMIN')
    DEFAULT 'USER',

    isActive BOOLEAN DEFAULT TRUE,

    refreshToken VARCHAR(500) DEFAULT NULL,
    refreshTokenExpiresAt DATETIME DEFAULT NULL,

    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);